name: Marine Biological Observation Dataset Registration
description: Provide Dataset Title and Description. Use this issue to log datasets you intend to mobilize to Darwin Core. 
title: "[dataset]: "
labels: ["data help","2023 Workshop"]
assignees:
  - sformel-usgs
  - timvdstap
body:
  - type: markdown
    attributes:
      value: |
        Use this form to provide a title, description and any (anticipated) blockers for the dataset you will be aligning to Darwin Core. For example, during the 2023 Biological Data Mobilization Workshop.
  - type: input
    id: primary_contact
    attributes:
      label: Contact details
      description: Your contact email address.
      placeholder: e.g. tim.vanderstap@hakai.org
    validations:
      required: true
  - type: input
    id: dataset_title
    attributes:
      label: Dataset Title
      description: A short title used to refer to your dataset.
      placeholder: e.g. Florida Keys Zooplankton 2018 Dataset
    validations:
      required: true
  - type: textarea
    id: descrip
    attributes:
      label: Describe your dataset and any specific challenges or blockers you have or anticipate.
      description: Dataset description and any specific dataset formatting challenges you have or anticipate.
      placeholder: I am working with data on.. and want help with..
    validations:
      required: true
  - type: input
    id: link_to_raw_files
    attributes:
      label: Info about "raw" Data Files.
      description: Description (and|or) link to the "raw" data files. 
      placeholder: The "raw" data is in one big really big excel file with no headers; the raw data can be downloaded from the following link [google drive link]
    validations:
      required: false
