---
title: "Basic overview of subset of OBIS occurrence data"
author: ~
date: '2019-07-23'
categories: []
tags: []
---


# fetch OBIS data using iobis/robis

```{r mpa compare imports, include=FALSE}
library(glue)
# also uses robis
source("./../R/obis_cache.R")
library(reticulate)
reticulate::use_python("python3")
```


```{r define region of interest}
# NOTE: This is not actually a MULTIPOLYGON; it's just a big rectangle.
#       Any WKT string can be used.
roi <- "MULTIPOLYGON (((-175 -80, 165 -80, 165 75, -175 75, -175 -80)))"
# special use areas manually transcribed from images at
# https://floridakeys.noaa.gov/zones/special/welcome.html
# converted from min/degrees to decimal degrees using
# https://www.pgc.umn.edu/apps/convert/
# https://floridakeys.noaa.gov/zones/special/easternsambo.html
```

```{r fetch occurrence data}
SPECIES_NAME <- "Balaenoptera musculus"
species_name_safe <- sanitize_query_id(SPECIES_NAME)
roi_query_id  <- glue( "query_id_placeholder_{species_name_safe}")
if (has_cache(roi_query_id)){
    occurrences <- load_cache(roi_query_id)
} else {
    occurrences <- robis::occurrence(
        SPECIES_NAME,
        geometry = roi
    )
    save_cache(roi_query_id, occurrences)
}
```

## explore occurrences in R

```{r occurrences timeseries, echo=FALSE}
ggplot2::ggplot(occurrences) + ggplot2::geom_bar(ggplot2::aes(date_year), width = 1)
```

```{r dataset contrib over time}
library(ggplot2)
ggplot() +
 geom_histogram(
     data=occurrences,
     aes(x=year, fill=datasetID),
     binwidth=5) +
 scale_fill_brewer(palette='Paired')
```

```{r map occurrences}
robis::map_leaflet(occurrences)
```

```{r custom map colored by dataset}
library(tidyverse)
library(leaflet)
color = "#ff3399"
provider_tiles = "OpenStreetMap.BlackAndWhite"
popup = function(x) { x["id"] }
p <- apply(occurrences, 1, popup)

# Create a continuous palette function
pal <- colorNumeric(
  palette = "Blues",
  domain = occurrences$latitude
)

# catagorical color palette
factpal <- colorFactor(topo.colors(5), occurrences$datasetID)

leaflet(occurrences) %>%
  addProviderTiles(provider_tiles) %>%
  addCircleMarkers(
      ~decimalLongitude, 
      ~decimalLatitude, 
      popup = p, 
      radius = 3, 
      weight = 1, 
      color = ~factpal(occurrences$datasetID),
      #fillColor = ~pal(occurrences$latitude), 
      #color = ~pal(occurrences$latitude), 
      opacity = 1, 
      fillOpacity = 0.1
  )
```

---------------------------------------------------------------------

# explore occurrences in python


```{python basic data access}
from pprint import pprint
# print head of records from R
type(r.occurrences)
#r.occurrences.head()

pprint(r.occurrences.columns)
```

```{python some pretty plots}
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame , read_csv

SELECTED_CATAGORICAL_COLUMNS = ['country', 'language', 'dropped', 'occurrenceStatus', 'modified', 'organismQuantity', 'sampleSizeUnit', 'dataset_id', 'license', 'organismQuantityType', 'scientificNameAuthorship', 'absence', 'vernacularName', 'specificEpithet', 'datasetID', 'category', 'sampleSizeValue', 'node_id', 'bibliographicCitation', 'continent', 'identificationReferences', 'fieldNumber', 'coordinateUncertaintyInMeters', 'taxonRemarks', 'behavior', 'informationWithheld', 'samplingEffort', 'dataGeneralizations']
TOP_N = 3  # show just the top N
fig, axes = plt.subplots(nrows=len(SELECTED_CATAGORICAL_COLUMNS), ncols=1, figsize=(8,len(SELECTED_CATAGORICAL_COLUMNS)*4))
for plot_i, column in enumerate(SELECTED_CATAGORICAL_COLUMNS):
    print("plotting top {} values for column '{}'".format(TOP_N, column))
    axis = axes[plot_i]
    counts  = r.occurrences[column].value_counts()
    #print(list(counts.index)[:TOP_N])
    #print(counts.values[:TOP_N])
    sns.barplot(list(counts.index)[:TOP_N], counts.values[:TOP_N], alpha=0.8, ax=axis)
    axis.title.set_text('Top {} "{}" for {}'.format(TOP_N, column, r.SPECIES_NAME))
    #axis.ylabel.set_text('# Occurrences', fontsize=12)
    #axis.xlabel.set_text(column, fontsize=12)
```

```{python show unused columns}

# print out columns we aren't looking at
unused_cols = r.occurrences.columns
for used_list in [SELECTED_CATAGORICAL_COLUMNS]:
    unused_cols = [x for x in unused_cols if x not in used_list]
print("unhandled columns: ", unused_cols)
```

