---
title: "README"
author: "Brett Johnson"
date: "10/02/2020"
output: html_document
---

# Hakai Institute Juvenile Salmon Program

The Hakai Institute Juvenile Salmon Program has been monitoring juvenile salmon migrations in the Discovery Islands and Johnstone Strait in British Columbia Canada, since 2015 to understand how ocean conditions experienced by juvenile salmon during their early marine migration impacts their growth, health and ultimately survival.

One of the goals of the Hakai Institute and the Canadian Integrated Ocean Observing System (CIOOS) is to facilitate Open Science and FAIR (findable, accessible, interoperable, reusable) ecological and oceanographic data. In a concerted effort to adopt or establish how best to do that, several Hakai and CIOOS staff attended an International Ocean Observing System (IOOS) Code Sprint in Ann Arbour, Michigan between October 7--11, 2019, to discuss how to implement FAIR data principles for biological data collected in the marine environment. 

The [Darwin Core](https://dwc.tdwg.org) is a highly structured data format that standardizes data table relations, vocabularies, and defines field names. The Darwin Core defines three table types: `event`, `occurrence`, and `measurementOrFact`. This intuitively captures the way most ecologists conduct their research. Typically, a survey (event) is conducted and measurements, counts, or observations (collectively measurementOrFacts) are made regarding a specific habitat or species (occurrence). 

See the salmon-darwin-core-remap.Rmd file for a complete account of the data transformation.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

