name: Publish Quarto book

on:
  push:
     branches: 
       - main
  workflow_dispatch:

# Deny all permissions by default
permissions: {}

jobs:
  build-deploy:
    name: Render & publish Quarto book
    runs-on: macOS-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b  # v2.2.0
        # with:
        #   tinytex: true  # for pdf but buggy on finding version
        
      # - name: Install chromium for Quarto     
      #   # for rendering Mermaid diagrams to pdf: https://quarto.org/docs/authoring/diagrams.html#chrome-install
      #   run: quarto install chromium

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05  # v2
      
      - name: Install librsvg
        # convert svg to png for pdf
        run: brew install librsvg
        
      - name: Install R
        uses: r-lib/actions/setup-r@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05  # v2
        with:
          r-version: '4.4.1'     # 2024-09-04

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05  # v2
        with:
          cache-version: 2
          
      - name: Prep files for Quarto render 
        # copy eDNA README.md to .qmd (placeholder for _quarto.yml)
        # necessary for `quarter render` to work, and before pre-render script overwrites .qmd
        run: cp datasets/dataset-edna/README.md datasets/dataset-edna/README.qmd

      - name: Quarto Render and Publish
        # TODO: `quarto publish gh-pages` https://quarto.org/docs/publishing/github-pages.html#publishing
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b  # v2.2.0
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
